spring:
  datasource:
    database: afisha
    url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.database}?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: true
  liquibase:
    contexts: dev
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  thymeleaf:
    enabled: true
server:
  port: 28010
log4j:
  logger:
    org:
      hibernate:
        SQL: debug
        type: trace
club:
  files:
    directory: /tmp
mail:
  host: smtp.yandex.ru
  port: 587
  protocol: smtp
  default-encoding: UTF-8
  username: info-dev@republic-club.by
  password: 1qaz@#WESDXC

bepaid:
  payment:
    test: true
    store:
      id: 363
      key: 4f585d2709776e53d080f36872fd1b63b700733e7624dfcadd057296daa37df6



# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#spring.datasource.url=jdbc:mysql://localhost:3306/jpa_many_to_many_demo?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=root
#
## Hibernate
#
## The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update
#
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE


net:
  sf:
    jasperreports:
      default:
        font:
          name: Serif
          size: 12
        pdf:
          font:
            name: Serif
            encoding: utf8
            embedded: false
